### ISSUE TITLE
Degree supervisor 

### ISSUE THREAD

**Issue by juhahakala** [dcmi/dc-srap#13]
Proposed URI: http://id.loc.gov/vocabulary/relators/dgs

Label: Supervisor

Recommended practice is to identify the supervisor with a URI. If this is not possible or feasible, a literal value that identifies the supervisor may be provided. It is also possible to give both the name and the URI.

Subproperty of: Contributor (http://purl.org/dc/elements/1.1/contributor)
		(http://purl.org/dc/terms/contributor)

Example <dcterms:supervisor id=https://isni.org/isni/00000001144261587 > Shannon, Claude</dcterms:supervisor>

**Comment by HughP** [comment]
@juhahakala @tombaker There are a lot of great ideas here in DC-SRAP. I'm wondering, rather than adding specific labels like "Supervisor" to contributor... why not just add the MARC roles vocabulary as a recognized vocabulary on the contributor and creator elements? It seems that there are other externally managed vocabularies such as LCSH for the subject element. Why not just add MARC relator roles in the same way? Is there a document which lays out the argument against or pitfalls of the approach which adds a vocabulary?

**Comment by juhahakala** [comment]
We are already using URLs of MARC relator codes in the draft SRAP spec to indicate semantic interoperability between proposed SRAP terms and MARC relators. URI of the MARC relator code Degree supervisor in the SRAP Supervisor specification is an example of this. The question is therefore that of how to express role information in DC. We can express Supervisor as an independent term, or as Contributor with the MARC relator role Degree supervisor. As far as I am concerned, both options are possible, but if we establish syntax which allows the use of MARC relator roles with Contributor and other relevant DC elements such as Publisher, it would be easy to extend the scope of DC well beyond the needs of SRAP. And migration of DC records to MARC 21 would probably be a bit more simple than it would otherwise be.

**Comment by HughP** [comment]
I agree, that the issue is how to express MARC roles about values in contributor fields... for many years the recommendation that made the most sense to me was to use something like `marcrel:edt` which was based on the [HTML implementation](https://www.dublincore.org/specifications/dublin-core/dc-html/). Working from an OAI-PMH perspective, we don't currently have a way to dereferences LCSH with a URL if we choose to use text in the value field... we could use uri's in the value field, but this leads the general problem you are trying to solve being able to use both... 

In contexts where one is looking to reduce verbosity the following pattern as used in OAI for qualified dublin core makes sense: 

## Qualified DC example

```
<dc:type xsi:type="dcterms:DCMIType">Event</dc:type>
```

## MARC role example

```
<dc:contributor xsi:type="dcterms:marcrel marcrel:aut">William Hall</dc:contributor>
```

## Subject example

```
<dc:subject xsi:type="dcterms:LCSH">Water</dc:subject>
```

## Language example

```
<dc:language xsi:type="dcterms:ISO639-3">eng</dc:subject>
```

That is, there ought to be implementation possibilities without using URIs such as in the MARC role example. 

It seems that variations of this data construct "problem" exists for dc.identifier, dc.language, dc.contributor, dc.subject, and dc.creator. But I veer off-topic for this github issue.

**Comment by juhahakala** [comment]
Preferred choice is to use LoC Relator code Degree supervisor. Technical questions related to how to express degree supervisor in various formats will be solved separately. Proposed solution should be applicable to other roles as well.
