### ISSUE TITLE
Resource missing/lost

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dc-srap#21]
The group has decided this is different from publication status. It appears to have an element of institutional holdings. While it may be that a service or publisher fails, it isn't clear how likely one would be to assign this availability status to all relevant individual articles. Such a failure may be best noted at a publisher level. (Note: there is some assignment of access rights at the publisher level as well. Those rights may filter down to individual resources but there may be a reason to assign them to a publisher or service.)

Also note that this status may have different meaning with hard copy resources (e.g. the library's copy is missing) vs digital resources (404 not found).

**Comment by juhahakala** [comment]
Further information on the use of date lost/date missing has been added to the profile (see https://github.com/dcmi/dc-srap/blob/main/profile/srap-profile.md for the new Markdown version) to address (tentatively) the issues Karen has brought up: 

Date lost should be used when e.g. the only known copy of a digital or printed resource has been destroyed or otherwise rendered unusable. 

Date lost should not be used when a publisher fails but its resources (e.g. serials) are still preserved in a legal deposit collection. Rights metadata should be updated to reflect changes in restrictions on access and use of such archived resources.  For serials and other continuing publications, the most convenient solution is to provide this metadata in the host record, from which it may be copied to all component part (article) records. 

Date missing may be used when e.g. a printed copy (item) of a resource has disappeared and its current location is unknown for the time being.

**Comment by kcoyle** [comment]
I understand that it is intended that "lost" is a permanent condition and "missing" MAY be temporary. Unfortunately that isn't consistent with natural use of those terms and I'm afraid that it won't be immediately obvious to anyone trying to use the terms. In fact, "missing" and "lost" are given as synonyms in the dictionary. I also cannot find a good single word that would convey that permanence needed for "lost". It may be necessary to expand that to "permanentLoss" or something like that. I'm combing through the thesaurus with the hope of finding something better.

**Comment by juhahakala** [comment]
permanentLoss seems like a good choice, unless we find a term that would be spot on for this purpose. Let's discuss this in our meeting 2022-10-11 (today).

**Comment by osma** [comment]
HTTP has [410 Gone](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410)

**Comment by juhahakala** [comment]
Following definitions have been agreed on: 

Date missing: 

Recommended practice is to provide this date only if there is no reasonable doubt that the resource is missing; that is, there may be one or more copies left but they cannot be found. Criteria for making the decision that the resource is missing may be developed locally. A SRAP record with date missing should have sufficient metadata to serve as a temporary tombstone of the resource.

Date missing may be used when e.g. a printed copy (item) of a resource has disappeared and its current location is unknown for the time being.

Date lost:

Recommended practice is to provide this date only if there is no reasonable doubt that the resource has been lost; that is, there is not a single (readable) copy of it left. Criteria for making the decision that the resource has been lost may be developed locally, but can include for instance digital documents that can no longer be rendered. A SRAP record with date lost should contain sufficient metadata to serve as a permanent tombstone of the resource.

Date lost should be used when e.g. the only known copy of a digital or printed resource has been destroyed or otherwise rendered unusable.

Date lost should not be used when a publisher fails but its resources (e.g. serials) are still preserved in a legal deposit collection. Rights metadata should be updated to reflect changes in restrictions on access and use of such archived resources. For serials and other continuing publications, the most convenient solution is to provide this metadata in the host record, from which it may be copied to all component part (article) records.
